### ISSUE TITLE
Button Click in Fragment

### ISSUE THREAD

**Issue by snipervld** [Julien-Mialon/StormXamarin#3] opened 2015-09-18 15:12 UTC
Hello (again). I have another issue. When i click a button in fragment, button's attached ICommand execute twice.

https://onedrive.live.com/redir?resid=BE878B196C95461B!1057&authkey=!ADrXEDjtl4gcsvk&ithint=file%2crar

**Comment by snipervld** [comment] 2015-09-18 15:13
AlertDialog shows twice (when you click OK, another AlertDialog appears)

**Comment by Julien-Mialon** [comment] 2015-09-21 07:51
This is weird, I never encountered this before. I'm gonna look into it asap.

**Comment by Julien-Mialon** [comment] 2015-09-21 22:04
Hello,

This is now fixed in version 1.2.20, caused by setting view models two times in fragment.

**Closed as completed by Julien-Mialon** 2015-09-21 22:04 UTC
Labels: bug
